In [1]:
import seaborn as sns
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv("train.txt", sep= ';', header=None,names= ['text', 'emotions'])

In [3]:
df.head()

                                                text emotions
0                            i didnt feel humiliated  sadness
1  i can go from feeling so hopeless to so damned...  sadness
2   im grabbing a minute to post i feel greedy wrong    anger
3  i am ever feeling nostalgic about the fireplac...     love
4                               i am feeling grouchy    anger

In [4]:
df.isnull().sum()

text        0
emotions    0
dtype: int64

In [5]:
emotions = df['emotions'].unique()

In [6]:
emo_numbers = {}
i = 0
for emo in emotions:
    emo_numbers[emo]= i
    i+=1
df['emotions'] = df['emotions'].map(emo_numbers)

In [7]:
df

                                                    text  emotions
0                                i didnt feel humiliated         0
1      i can go from feeling so hopeless to so damned...         0
2       im grabbing a minute to post i feel greedy wrong         1
3      i am ever feeling nostalgic about the fireplac...         2
4                                   i am feeling grouchy         1
...                                                  ...       ...
15995  i just had a very brief time in the beanbag an...         0
15996  i am now turning and i feel pathetic that i am...         0
15997                     i feel strong and good overall         5
15998  i feel like this was such a rude comment and i...         1
15999  i know a lot but i feel so stupid because i ca...         0

[16000 rows x 2 columns]

In [8]:
!pip install spacy

Requirement already satisfied: spacy in C:\Users\admin\AppData\Local\Programs\Python\Python314\Lib\site-packages (3.8.16)
Requirement already satisfied: spacy-legacy<3.1.0,>=3.0.11 in C:\Users\admin\AppData\Local\Programs\Python\Python314\Lib\site-packages (from spacy) (3.0.12)
Requirement already satisfied: spacy-loggers<2.0.0,>=1.0.0 in C:\Users\admin\AppData\Local\Programs\Python\Python314\Lib\site-packages (from spacy) (1.0.5)
Requirement already satisfied: murmurhash<1.1.0,>=0.28.0 in C:\Users\admin\AppData\Local\Programs\Python\Python314\Lib\site-packages (from spacy) (1.0.15)
Requirement already satisfied: cymem<2.1.0,>=2.0.2 in C:\Users\admin\AppData\Local\Programs\Python\Python314\Lib\site-packages (from spacy) (2.0.13)
Requirement already satisfied: preshed<3.1.0,>=3.0.2 in C:\Users\admin\AppData\Local\Programs\Python\Python314\Lib\site-packages (from spacy) (3.0.13)
Requirement already satisfied: thinc<8.4.0,>=8.3.12 in C:\Users\admin\AppData\Local\Programs\Python\Python314\Lib\site-packages (from spacy) (8.3.13)
Requirement already satisfied: wasabi<1.2.0,>=0.9.1 in C:\Users\admin\AppData\Local\Programs\Python\Python314\Lib\site-packages (from spacy) (1.1.3)
Requirement already satisfied: srsly<3.0.0,>=2.5.3 in C:\Users\admin\AppData\Local\Programs\Python\Python314\Lib\site-packages (from spacy) (2.5.3)
Requirement already satisfied: catalogue<2.1.0,>=2.0.6 in C:\Users\admin\AppData\Local\Programs\Python\Python314\Lib\site-packages (from spacy) (2.0.10)
Requirement already satisfied: weasel<2.0.0,>=1.0.0 in C:\Users\admin\AppData\Local\Programs\Python\Python314\Lib\site-packages (from spacy) (1.0.0)
Requirement already satisfied: confection<2.0.0,>=1.3.2 in C:\Users\admin\AppData\Local\Programs\Python\Python314\Lib\site-packages (from spacy) (1.3.3)
Requirement already satisfied: typer<1.0.0,>=0.3.0 in C:\Users\admin\AppData\Local\Programs\Python\Python314\Lib\site-packages (from spacy) (0.27.2)
Requirement already satisfied: click<9.0.0,>=8.2.1 in C:\Users\admin\AppData\Local\Programs\Python\Python314\Lib\site-packages (from spacy) (8.4.2)
Requirement already satisfied: tqdm<5.0.0,>=4.38.0 in C:\Users\admin\AppData\Local\Programs\Python\Python314\Lib\site-packages (from spacy) (4.70.1)
Requirement already satisfied: numpy>=1.19.0 in C:\Users\admin\AppData\Local\Programs\Python\Python314\Lib\site-packages (from spacy) (2.5.1)
Requirement already satisfied: requests<3.0.0,>=2.13.0 in C:\Users\admin\AppData\Local\Programs\Python\Python314\Lib\site-packages (from spacy) (2.34.2)
Requirement already satisfied: pydantic<3.0.0,>=2.0.0 in C:\Users\admin\AppData\Local\Programs\Python\Python314\Lib\site-packages (from spacy) (2.13.5)
Requirement already satisfied: jinja2 in C:\Users\admin\AppData\Local\Programs\Python\Python314\Lib\site-packages (from spacy) (3.1.6)
Requirement already satisfied: setuptools in C:\Users\admin\AppData\Local\Programs\Python\Python314\Lib\site-packages (from spacy) (84.0.0)
Requirement already satisfied: packaging>=20.0 in C:\Users\admin\AppData\Local\Programs\Python\Python314\Lib\site-packages (from spacy) (26.2)
Requirement already satisfied: colorama in C:\Users\admin\AppData\Local\Programs\Python\Python314\Lib\site-packages (from click<9.0.0,>=8.2.1->spacy) (0.4.6)
Requirement already satisfied: annotated-types>=0.6.0 in C:\Users\admin\AppData\Local\Programs\Python\Python314\Lib\site-packages (from pydantic<3.0.0,>=2.0.0->spacy) (0.8.0)
Requirement already satisfied: pydantic-core==2.46.5 in C:\Users\admin\AppData\Local\Programs\Python\Python314\Lib\site-packages (from pydantic<3.0.0,>=2.0.0->spacy) (2.46.5)
Requirement already satisfied: typing-extensions>=4.14.1 in C:\Users\admin\AppData\Local\Programs\Python\Python314\Lib\site-packages (from pydantic<3.0.0,>=2.0.0->spacy) (4.16.0)
Requirement already satisfied: typing-inspection>=0.4.2 in C:\Users\admin\AppData\Local\Programs\Python\Python314\Lib\site-packages (from pydantic<3.0.0,>=2.0.0->spacy) (0.4.4)
Requirement already satisfied: charset_normalizer<4,>=2 in C:\Users\admin\AppData\Local\Programs\Python\Python314\Lib\site-packages (from requests<3.0.0,>=2.13.0->spacy) (3.4.9)
Requirement already satisfied: idna<4,>=2.5 in C:\Users\admin\AppData\Local\Programs\Python\Python314\Lib\site-packages (from requests<3.0.0,>=2.13.0->spacy) (3.18)
Requirement already satisfied: urllib3<3,>=1.26 in C:\Users\admin\AppData\Local\Programs\Python\Python314\Lib\site-packages (from requests<3.0.0,>=2.13.0->spacy) (2.7.0)
Requirement already satisfied: certifi>=2023.5.7 in C:\Users\admin\AppData\Local\Programs\Python\Python314\Lib\site-packages (from requests<3.0.0,>=2.13.0->spacy) (2026.7.22)
Requirement already satisfied: blis<1.4.0,>=1.3.0 in C:\Users\admin\AppData\Local\Programs\Python\Python314\Lib\site-packages (from thinc<8.4.0,>=8.3.12->spacy) (1.3.3)
Requirement already satisfied: shellingham>=1.3.0 in C:\Users\admin\AppData\Local\Programs\Python\Python314\Lib\site-packages (from typer<1.0.0,>=0.3.0->spacy) (1.5.4)
Requirement already satisfied: rich>=13.8.0 in C:\Users\admin\AppData\Local\Programs\Python\Python314\Lib\site-packages (from typer<1.0.0,>=0.3.0->spacy) (15.0.0)
Requirement already satisfied: annotated-doc>=0.0.2 in C:\Users\admin\AppData\Local\Programs\Python\Python314\Lib\site-packages (from typer<1.0.0,>=0.3.0->spacy) (0.0.5)
Requirement already satisfied: cloudpathlib>=0.7.0 in C:\Users\admin\AppData\Local\Programs\Python\Python314\Lib\site-packages (from weasel<2.0.0,>=1.0.0->spacy) (0.25.0)
Requirement already satisfied: smart-open>=5.2.1 in C:\Users\admin\AppData\Local\Programs\Python\Python314\Lib\site-packages (from weasel<2.0.0,>=1.0.0->spacy) (8.0.1)
Requirement already satisfied: httpx>=0.24.0 in C:\Users\admin\AppData\Local\Programs\Python\Python314\Lib\site-packages (from weasel<2.0.0,>=1.0.0->spacy) (0.28.1)
Requirement already satisfied: anyio in C:\Users\admin\AppData\Local\Programs\Python\Python314\Lib\site-packages (from httpx>=0.24.0->weasel<2.0.0,>=1.0.0->spacy) (4.14.2)
Requirement already satisfied: httpcore==1.* in C:\Users\admin\AppData\Local\Programs\Python\Python314\Lib\site-packages (from httpx>=0.24.0->weasel<2.0.0,>=1.0.0->spacy) (1.0.9)
Requirement already satisfied: h11>=0.16 in C:\Users\admin\AppData\Local\Programs\Python\Python314\Lib\site-packages (from httpcore==1.*->httpx>=0.24.0->weasel<2.0.0,>=1.0.0->spacy) (0.16.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in C:\Users\admin\AppData\Local\Programs\Python\Python314\Lib\site-packages (from rich>=13.8.0->typer<1.0.0,>=0.3.0->spacy) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in C:\Users\admin\AppData\Local\Programs\Python\Python314\Lib\site-packages (from rich>=13.8.0->typer<1.0.0,>=0.3.0->spacy) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in C:\Users\admin\AppData\Local\Programs\Python\Python314\Lib\site-packages (from markdown-it-py>=2.2.0->rich>=13.8.0->typer<1.0.0,>=0.3.0->spacy) (0.1.2)
Requirement already satisfied: wrapt in C:\Users\admin\AppData\Local\Programs\Python\Python314\Lib\site-packages (from smart-open>=5.2.1->weasel<2.0.0,>=1.0.0->spacy) (2.4.1)
Requirement already satisfied: MarkupSafe>=2.0 in C:\Users\admin\AppData\Local\Programs\Python\Python314\Lib\site-packages (from jinja2->spacy) (3.0.3)

[notice] A new release of pip is available: 26.1.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [9]:
!python -m spacy download en_core_web_sm

Collecting en-core-web-sm==3.8.0
  Downloading en_core_web_sm-3.8.0-py3-none-any.whl (12.8 MB)
     ---------------------------------------- 0.0/12.8 MB ? eta -:--:--
     ---------------------------------------- 0.0/12.8 MB ? eta -:--:--
     ---------------------------------------- 0.0/12.8 MB ? eta -:--:--
     ---------------------------------------- 0.0/12.8 MB ? eta -:--:--
     ---------------------------------------- 0.0/12.8 MB ? eta -:--:--
      --------------------------------------- 0.3/12.8 MB ? eta -:--:--
      --------------------------------------- 0.3/12.8 MB ? eta -:--:--
      --------------------------------------- 0.3/12.8 MB ? eta -:--:--
     - ------------------------------------- 0.5/12.8 MB 467.2 kB/s eta 0:00:27
     - ------------------------------------- 0.5/12.8 MB 467.2 kB/s eta 0:00:27
     -- ------------------------------------ 0.8/12.8 MB 478.1 kB/s eta 0:00:26
     -- ------------------------------------ 0.8/12.8 MB 478.1 kB/s eta 0:00:26
     -- ------------------------------------ 0.8/12.8 MB 478.1 kB/s eta 0:00:26
     --- ----------------------------------- 1.0/12.8 MB 477.9 kB/s eta 0:00:25
     --- ----------------------------------- 1.0/12.8 MB 477.9 kB/s eta 0:00:25
     --- ----------------------------------- 1.3/12.8 MB 475.5 kB/s eta 0:00:25
     --- ----------------------------------- 1.3/12.8 MB 475.5 kB/s eta 0:00:25
     --- ----------------------------------- 1.3/12.8 MB 475.5 kB/s eta 0:00:25
     ---- ---------------------------------- 1.6/12.8 MB 482.9 kB/s eta 0:00:24
     ---- ---------------------------------- 1.6/12.8 MB 482.9 kB/s eta 0:00:24
     ----- --------------------------------- 1.8/12.8 MB 484.5 kB/s eta 0:00:23
     ----- --------------------------------- 1.8/12.8 MB 484.5 kB/s eta 0:00:23
     ----- --------------------------------- 1.8/12.8 MB 484.5 kB/s eta 0:00:23
     ------ -------------------------------- 2.1/12.8 MB 484.8 kB/s eta 0:00:23
     ------ -------------------------------- 2.1/12.8 MB 484.8 kB/s eta 0:00:23
     ------ -------------------------------- 2.1/12.8 MB 484.8 kB/s eta 0:00:23
     ------ -------------------------------- 2.1/12.8 MB 484.8 kB/s eta 0:00:23
     ------- ------------------------------- 2.4/12.8 MB 442.5 kB/s eta 0:00:24
     ------- ------------------------------- 2.4/12.8 MB 442.5 kB/s eta 0:00:24
     ------- ------------------------------- 2.4/12.8 MB 442.5 kB/s eta 0:00:24
     ------- ------------------------------- 2.4/12.8 MB 442.5 kB/s eta 0:00:24
     ------- ------------------------------- 2.4/12.8 MB 442.5 kB/s eta 0:00:24
     ------- ------------------------------- 2.4/12.8 MB 442.5 kB/s eta 0:00:24
     ------- ------------------------------- 2.4/12.8 MB 442.5 kB/s eta 0:00:24
     ------- ------------------------------- 2.6/12.8 MB 376.9 kB/s eta 0:00:28
     ------- ------------------------------- 2.6/12.8 MB 376.9 kB/s eta 0:00:28
     ------- ------------------------------- 2.6/12.8 MB 376.9 kB/s eta 0:00:28
     ------- ------------------------------- 2.6/12.8 MB 376.9 kB/s eta 0:00:28
     ------- ------------------------------- 2.6/12.8 MB 376.9 kB/s eta 0:00:28
     -------- ------------------------------ 2.9/12.8 MB 362.6 kB/s eta 0:00:28
     -------- ------------------------------ 2.9/12.8 MB 362.6 kB/s eta 0:00:28
     --------- ----------------------------- 3.1/12.8 MB 372.3 kB/s eta 0:00:26
     --------- ----------------------------- 3.1/12.8 MB 372.3 kB/s eta 0:00:26
     --------- ----------------------------- 3.1/12.8 MB 372.3 kB/s eta 0:00:26
     ---------- ---------------------------- 3.4/12.8 MB 377.7 kB/s eta 0:00:25
     ---------- ---------------------------- 3.4/12.8 MB 377.7 kB/s eta 0:00:25
     ---------- ---------------------------- 3.4/12.8 MB 377.7 kB/s eta 0:00:25
     ----------- --------------------------- 3.7/12.8 MB 383.2 kB/s eta 0:00:24
     ----------- --------------------------- 3.7/12.8 MB 383.2 kB/s eta 0:00:24
     ----------- --------------------------- 3.9/12.8 MB 388.3 kB/s eta 0:00:23
     ----------- --------------------------- 3.9/12.8 MB 388.3 kB/s eta 0:00:23
     ----------- --------------------------- 3.9/12.8 MB 388.3 kB/s eta 0:00:23
     ------------ -------------------------- 4.2/12.8 MB 392.0 kB/s eta 0:00:22
     ------------ -------------------------- 4.2/12.8 MB 392.0 kB/s eta 0:00:22
     ------------- ------------------------- 4.5/12.8 MB 396.8 kB/s eta 0:00:22
     ------------- ------------------------- 4.5/12.8 MB 396.8 kB/s eta 0:00:22
     ------------- ------------------------- 4.5/12.8 MB 396.8 kB/s eta 0:00:22
     -------------- ------------------------ 4.7/12.8 MB 401.2 kB/s eta 0:00:21
     -------------- ------------------------ 4.7/12.8 MB 401.2 kB/s eta 0:00:21
     -------------- ------------------------ 4.7/12.8 MB 401.2 kB/s eta 0:00:21
     --------------- ----------------------- 5.0/12.8 MB 405.1 kB/s eta 0:00:20
     --------------- ----------------------- 5.0/12.8 MB 405.1 kB/s eta 0:00:20
     --------------- ----------------------- 5.2/12.8 MB 407.8 kB/s eta 0:00:19
     --------------- ----------------------- 5.2/12.8 MB 407.8 kB/s eta 0:00:19
     --------------- ----------------------- 5.2/12.8 MB 407.8 kB/s eta 0:00:19
     ---------------- ---------------------- 5.5/12.8 MB 411.1 kB/s eta 0:00:18
     ---------------- ---------------------- 5.5/12.8 MB 411.1 kB/s eta 0:00:18
     ---------------- ---------------------- 5.5/12.8 MB 411.1 kB/s eta 0:00:18
     ----------------- --------------------- 5.8/12.8 MB 412.3 kB/s eta 0:00:18
     ----------------- --------------------- 5.8/12.8 MB 412.3 kB/s eta 0:00:18
     ------------------ -------------------- 6.0/12.8 MB 414.1 kB/s eta 0:00:17
     ------------------ -------------------- 6.0/12.8 MB 414.1 kB/s eta 0:00:17
     ------------------ -------------------- 6.0/12.8 MB 414.1 kB/s eta 0:00:17
     ------------------- ------------------- 6.3/12.8 MB 416.9 kB/s eta 0:00:16
     ------------------- ------------------- 6.3/12.8 MB 416.9 kB/s eta 0:00:16
     ------------------- ------------------- 6.3/12.8 MB 416.9 kB/s eta 0:00:16
     ------------------- ------------------- 6.6/12.8 MB 418.2 kB/s eta 0:00:15
     ------------------- ------------------- 6.6/12.8 MB 418.2 kB/s eta 0:00:15
     ------------------- ------------------- 6.6/12.8 MB 418.2 kB/s eta 0:00:15
     ------------------- ------------------- 6.6/12.8 MB 418.2 kB/s eta 0:00:15
     ------------------- ------------------- 6.6/12.8 MB 418.2 kB/s eta 0:00:15
     ------------------- ------------------- 6.6/12.8 MB 418.2 kB/s eta 0:00:15
     -------------------- ------------------ 6.8/12.8 MB 401.4 kB/s eta 0:00:15
     -------------------- ------------------ 6.8/12.8 MB 401.4 kB/s eta 0:00:15
     -------------------- ------------------ 6.8/12.8 MB 401.4 kB/s eta 0:00:15
     -------------------- ------------------ 6.8/12.8 MB 401.4 kB/s eta 0:00:15
     -------------------- ------------------ 6.8/12.8 MB 401.4 kB/s eta 0:00:15
     -------------------- ------------------ 6.8/12.8 MB 401.4 kB/s eta 0:00:15
     -------------------- ------------------ 6.8/12.8 MB 401.4 kB/s eta 0:00:15
     --------------------- ----------------- 7.1/12.8 MB 382.9 kB/s eta 0:00:15
     --------------------- ----------------- 7.1/12.8 MB 382.9 kB/s eta 0:00:15
     --------------------- ----------------- 7.1/12.8 MB 382.9 kB/s eta 0:00:15
     --------------------- ----------------- 7.1/12.8 MB 382.9 kB/s eta 0:00:15
     ---------------------- ---------------- 7.3/12.8 MB 379.3 kB/s eta 0:00:15
     ---------------------- ---------------- 7.3/12.8 MB 379.3 kB/s eta 0:00:15
     ---------------------- ---------------- 7.3/12.8 MB 379.3 kB/s eta 0:00:15
     ----------------------- --------------- 7.6/12.8 MB 377.6 kB/s eta 0:00:14
     ----------------------- --------------- 7.6/12.8 MB 377.6 kB/s eta 0:00:14
     ----------------------- --------------- 7.6/12.8 MB 377.6 kB/s eta 0:00:14
     ----------------------- --------------- 7.6/12.8 MB 377.6 kB/s eta 0:00:14
     ----------------------- --------------- 7.6/12.8 MB 377.6 kB/s eta 0:00:14
     ----------------------- --------------- 7.9/12.8 MB 370.9 kB/s eta 0:00:14
     ----------------------- --------------- 7.9/12.8 MB 370.9 kB/s eta 0:00:14
     ----------------------- --------------- 7.9/12.8 MB 370.9 kB/s eta 0:00:14
     ----------------------- --------------- 7.9/12.8 MB 370.9 kB/s eta 0:00:14
     ------------------------ -------------- 8.1/12.8 MB 368.5 kB/s eta 0:00:13
     ------------------------ -------------- 8.1/12.8 MB 368.5 kB/s eta 0:00:13
     ------------------------ -------------- 8.1/12.8 MB 368.5 kB/s eta 0:00:13
     ------------------------ -------------- 8.1/12.8 MB 368.5 kB/s eta 0:00:13
     ------------------------- ------------- 8.4/12.8 MB 366.5 kB/s eta 0:00:13
     ------------------------- ------------- 8.4/12.8 MB 366.5 kB/s eta 0:00:13
     ------------------------- ------------- 8.4/12.8 MB 366.5 kB/s eta 0:00:13
     ------------------------- ------------- 8.4/12.8 MB 366.5 kB/s eta 0:00:13
     -------------------------- ------------ 8.7/12.8 MB 366.7 kB/s eta 0:00:12
     -------------------------- ------------ 8.7/12.8 MB 366.7 kB/s eta 0:00:12
     -------------------------- ------------ 8.7/12.8 MB 366.7 kB/s eta 0:00:12
     --------------------------- ----------- 8.9/12.8 MB 367.0 kB/s eta 0:00:11
     --------------------------- ----------- 8.9/12.8 MB 367.0 kB/s eta 0:00:11
     --------------------------- ----------- 8.9/12.8 MB 367.0 kB/s eta 0:00:11
     --------------------------- ----------- 9.2/12.8 MB 366.4 kB/s eta 0:00:10
     --------------------------- ----------- 9.2/12.8 MB 366.4 kB/s eta 0:00:10
     --------------------------- ----------- 9.2/12.8 MB 366.4 kB/s eta 0:00:10
     ---------------------------- ---------- 9.4/12.8 MB 367.4 kB/s eta 0:00:10
     ---------------------------- ---------- 9.4/12.8 MB 367.4 kB/s eta 0:00:10
     ---------------------------- ---------- 9.4/12.8 MB 367.4 kB/s eta 0:00:10
     ---------------------------- ---------- 9.4/12.8 MB 367.4 kB/s eta 0:00:10
     ---------------------------- ---------- 9.4/12.8 MB 367.4 kB/s eta 0:00:10
     ---------------------------- ---------- 9.4/12.8 MB 367.4 kB/s eta 0:00:10
     ----------------------------- --------- 9.7/12.8 MB 360.9 kB/s eta 0:00:09
     ----------------------------- --------- 9.7/12.8 MB 360.9 kB/s eta 0:00:09
     ----------------------------- --------- 9.7/12.8 MB 360.9 kB/s eta 0:00:09
     ----------------------------- --------- 9.7/12.8 MB 360.9 kB/s eta 0:00:09
     ----------------------------- --------- 9.7/12.8 MB 360.9 kB/s eta 0:00:09
     ----------------------------- --------- 9.7/12.8 MB 360.9 kB/s eta 0:00:09
     ----------------------------- --------- 9.7/12.8 MB 360.9 kB/s eta 0:00:09
     ----------------------------- -------- 10.0/12.8 MB 351.8 kB/s eta 0:00:09
     ----------------------------- -------- 10.0/12.8 MB 351.8 kB/s eta 0:00:09
     ----------------------------- -------- 10.0/12.8 MB 351.8 kB/s eta 0:00:09
     ----------------------------- -------- 10.0/12.8 MB 351.8 kB/s eta 0:00:09
     ----------------------------- -------- 10.0/12.8 MB 351.8 kB/s eta 0:00:09
     ----------------------------- -------- 10.0/12.8 MB 351.8 kB/s eta 0:00:09
     ----------------------------- -------- 10.0/12.8 MB 351.8 kB/s eta 0:00:09
     ------------------------------ ------- 10.2/12.8 MB 343.3 kB/s eta 0:00:08
     ------------------------------ ------- 10.2/12.8 MB 343.3 kB/s eta 0:00:08
     ------------------------------ ------- 10.2/12.8 MB 343.3 kB/s eta 0:00:08
     ------------------------------- ------ 10.5/12.8 MB 344.0 kB/s eta 0:00:07
     ------------------------------- ------ 10.5/12.8 MB 344.0 kB/s eta 0:00:07
     ------------------------------- ------ 10.5/12.8 MB 344.0 kB/s eta 0:00:07
     ------------------------------- ------ 10.7/12.8 MB 343.0 kB/s eta 0:00:07
     ------------------------------- ------ 10.7/12.8 MB 343.0 kB/s eta 0:00:07
     ------------------------------- ------ 10.7/12.8 MB 343.0 kB/s eta 0:00:07
     -------------------------------- ----- 11.0/12.8 MB 342.6 kB/s eta 0:00:06
     -------------------------------- ----- 11.0/12.8 MB 342.6 kB/s eta 0:00:06
     --------------------------------- ---- 11.3/12.8 MB 342.0 kB/s eta 0:00:05
     --------------------------------- ---- 11.3/12.8 MB 342.0 kB/s eta 0:00:05
     --------------------------------- ---- 11.3/12.8 MB 342.0 kB/s eta 0:00:05
     ---------------------------------- --- 11.5/12.8 MB 341.8 kB/s eta 0:00:04
     ---------------------------------- --- 11.5/12.8 MB 341.8 kB/s eta 0:00:04
     ---------------------------------- --- 11.5/12.8 MB 341.8 kB/s eta 0:00:04
     ----------------------------------- -- 11.8/12.8 MB 341.4 kB/s eta 0:00:03
     ----------------------------------- -- 11.8/12.8 MB 341.4 kB/s eta 0:00:03
     ----------------------------------- -- 12.1/12.8 MB 341.6 kB/s eta 0:00:03
     ----------------------------------- -- 12.1/12.8 MB 341.6 kB/s eta 0:00:03
     ----------------------------------- -- 12.1/12.8 MB 341.6 kB/s eta 0:00:03
     ------------------------------------ - 12.3/12.8 MB 341.8 kB/s eta 0:00:02
     ------------------------------------ - 12.3/12.8 MB 341.8 kB/s eta 0:00:02
     -------------------------------------  12.6/12.8 MB 346.4 kB/s eta 0:00:01
     -------------------------------------  12.6/12.8 MB 346.4 kB/s eta 0:00:01
     -------------------------------------  12.6/12.8 MB 346.4 kB/s eta 0:00:01
     ---------------------------------------- 12.8/12.8 MB 357.0 kB/s  0:00:35
[+] Download and installation successful
You can now load the package via spacy.load('en_core_web_sm')

[notice] A new release of pip is available: 26.1.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [10]:
import spacy

nlp = spacy.load("en_core_web_sm")

In [11]:
df["cleaned_text"] = df["text"].apply(
    lambda text: " ".join(
        token.text for token in nlp(text)
        if not token.is_stop
    )
)